export { AnalyticsProvider } from "./provider";
export {
  track,
  flush,
  setVariant,
  getSessionId,
  ensureSession,
  registerVisit,
  type VisitorRecord,
  trackPointsEntered,
  trackPointsEnteredDebounced,
  trackCardAdded,
  trackCardRemoved,
  trackMapPin,
  trackGate,
  trackFeedback,
  trackShare,
  trackSubscribe,
  trackContact,
  trackDonateIntent,
  trackChatOpened,
  trackChatMessage,
} from "./client";
export {
  EVENTS,
  EVENT_NAMES,
  isEventName,
  type EventName,
  type VariantKey,
  type Scale,
} from "./events";
